version: "3.9"

services:
  mariadb:
    build: requirements/mariadb
    restart: always
    expose:
      - "3306"
    environment:
    - MARIADB_ID=${MARIADB_ID}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - docker-network 

  nginx:
    image: debian:bullseye
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - docker-network 
  
  wordpress:
    image: debian:bullseye
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - docker-network 

volumes:
  db: {}
  data: {}

networks:
  docker-network:
    driver: bridge
