version: "3.9"

services:
  mariadb:
    build: requirements/mariadb
    restart: always
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker-network 

  # wordpress:
  #   image: debian:bullseye
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   expose:
  #     - "9000"
  #   networks:
  #     - docker-network 
  
  nginx:
    build: requirements/nginx
    restart: always
   # depends_on:
   #   - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker-network

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  docker-network:
    driver: bridge
