version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    expose:
      - "3306"
   network: docker-network
  workpress:
    image: workpress
    restart: always
    expose:
      - "9000"
    networks: docker-network
networks:
  docker-network:
    driver: bridge