version: '3'

volumes:
  data: {}

services:
  mariadb:
    build: requirements/mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - docker-network 
    environment:
    - MARIADB_ID=${MARIADB_ID}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  nginx:
    image: debian:bullseye
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - docker-network 
  
  wordpress:
    image: debian:bullseye
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - docker-network 

networks:
  docker-network:
    driver: bridge
