CREATE DATABASE wordpress_db;
CREATE USER '${MARIADB_ID}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL ON wordpress_db.* TO '${MARIADB_ID}'@'%';
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MARIADB_PASSWORD}');
FLUSH PRIVILEGES;