version: "3.7"

services:
  db: # docker run --name
    image: mysql:5.7
    volumes: # docker run -v(--volume)
      - ./db_data:/var/lib/mysql
    restart: always
    environment: # docker run -e : set 환경변수
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 123456
  
  app:
    depends_on: # 선행관계
      - db # db 컨테이너 먼저 실행됨
    image: wordpress:latest
    volumes:
      - ./app_data:/var/www/html
    ports: # docker run -p : port-forwading
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 123456 

# 외부에서 wordpress에는 접근가능해야하지만, 
# mysql에는 app 컨테이너만 접근하면 됨. 즉 외부에서 접근하지 않도록 만드는 게 안전 !
# shell과 달리, 
# docker-compose를 만드는 순간에 자동으로 network 만들어지고, 컨테이너들이 이 network에 연결됨.

